Upstream Sync
Forked Upstream Sync

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -1,49 +1,34 @@
-name: Actions
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  pull_request:
-    branches:
-      - main
-      - next
-  push:
-    branches:
-      - main
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
 
 jobs:
-  lint:
-    name: Lint
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v6.0.2
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-      - name: Set up Python
-        uses: actions/setup-python@v6
-        with:
-          python-version-file: ".python-version"
-          cache: "pip"
-          cache-dependency-path: "requirements.txt"
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
 
-      - name: Run pre-commit
-        uses: pre-commit/action@v3.0.1
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
+              with:
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+                  upstream_sync_repo: hacs/documentation
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
 
-  build:
-    name: Build
-    runs-on: ubuntu-latest
-    needs: lint
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v6.0.2
-
-      - name: Set up Python
-        uses: actions/setup-python@v6
-        with:
-          python-version-file: ".python-version"
-          cache: "pip"
-          cache-dependency-path: "requirements.txt"
-
-      - name: Setup
-        run: scripts/setup
-
-      - name: Build
-        run: scripts/build
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
